### ISSUE TITLE
Mouse cut and select: make them work with Blender 2.80's latest changes

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#355]
The VSE now uses left click for all selection-related operations. The keymap's pretty consistent and now I think Power Sequencer should respect that

Left click and drag to box select strips, and S-LClick and drag to add to the box selection. In left click select mode. Also, S-LClick and C-S-LClick are normally to add to the selection and select linked strips, C-LClick to toggle select strips on one side of the time cursor, and M-LClick to toggle select handles

## Tasks

- [x] Redesign the tool and interactions
- [ ] Get people to test the changes
- [ ] Rewrite drawing function to support the new design
- [ ] Write docs for the final version

## Ideas for changes

- M-LClick to toggle a strip visible isn't as useful now selecting is much easier: can use the H key to toggle strips hidden
- Move all cut operations to RClick? Note that S-RClick is the shortcut to scrub for now
- Remove box select operators

**Comment by NathanLovato** [comment]
I'm working on this in the mouse cut redesign branch: https://github.com/GDquest/Blender-power-sequencer/tree/mouse-cut-shortcuts-redesign

After a few hours playing with the design, I've got an interaction that kind of works, that's designed to work more like one of Blender's tools.

Could you test the design and tell me if it's pleasant to use?

- T to start the Trim tool
- the time cursor and preview update as you move the mouse around
- Click to insert a cut (acts like a Razor tool in other NLEs)
- Click and drag to trim
- Press Shift and Alt to toggle trimming all channels and remove gaps respectively
- Press T or RETURN to finish using the tool. The idea is that if we can turn this in a built-in tool later, it'll sit in a toolbar in the sequencer instead.

The drawing function doesn't work right now, I've got that left to fix, but I'd like to get the tool working as efficiently as possible before fixing bugs.

**Comment by NathanLovato** [comment]
Here's a test build to play with: [power-sequencer-1.3-trim-redesign.zip](https://github.com/GDquest/Blender-power-sequencer/files/3255688/power-sequencer-1.3-trim-redesign.zip)

**Comment by 3pointedit** [comment]
I just tried to load the addon but it doesn't appear in the addons list. I enabled Auto Run scripts. 
My Blender build is just a couple days old. Here's the build: version: 2.80 (sub 72), branch: blender2.7, commit date: 2019-05-28 21:07, hash: 9bae9b634ec6, type: Release
build date: 28/05/2019, 17:09
platform: Windows

**Comment by NathanLovato** [comment]
Indeed, I messed up the zip file. Here's a correct build: 
[power-sequencer-trim-tool-redesign.zip](https://github.com/GDquest/Blender-power-sequencer/files/3259950/power-sequencer-trim-tool-redesign.zip)

Known issues;

- Drawing is a bit off, the line moves up and down with your mouse cursor
- Sometimes doesn't draw depending on your zoom level, but the issue seems to come from Blender's view_to_region() function, I couldn't find a way to fix it.

**Comment by 3pointedit** [comment]
Ok its loading up now... trying it... OMG What!!!? Thats soo cool! 
Sorry for not showing appropriate decorum on the github :(

**Comment by 3pointedit** [comment]
It worked fine for a few clicks then the mouse-hold failed and it became a simple split. I could not reliably get it to perform the modifiers for all tracks. It slows down mouse performance after a few minutes. On windows 10

**Comment by brousselle** [comment]
sounds pretty good indeed :+1: 
i know this might be off topic, but anyone else annoyed by the new "Alt+leftClick" to select current frame ?
Anyone knows how to change it ? (this is conflicting with my desktop manager) ...
